# coding: utf-8

"""
    Lob

    The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 

    The version of the OpenAPI document: 1.19.28
    Contact: lob-openapi@lob.com
    Created by: https://support.lob.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lob_python_sdk import schemas  # noqa: F401


class AddressFieldsUs(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "address_line1",
            "address_state",
            "address_zip",
            "address_city",
        }
        
        class properties:
            
            
            class address_line1(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 64
            
            
            class address_city(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 200
            
            
            class address_state(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    regex=[{
                        'pattern': r'^[a-zA-Z]{2}$',
                    }]
            
            
            class address_zip(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    regex=[{
                        'pattern': r'^\d{5}(-\d{4})?$',
                    }]
            
            
            class address_line2(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 64
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'address_line2':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "address_line1": address_line1,
                "address_city": address_city,
                "address_state": address_state,
                "address_zip": address_zip,
                "address_line2": address_line2,
            }
    
    address_line1: MetaOapg.properties.address_line1
    address_state: MetaOapg.properties.address_state
    address_zip: MetaOapg.properties.address_zip
    address_city: MetaOapg.properties.address_city
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["address_line1"]) -> MetaOapg.properties.address_line1: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["address_city"]) -> MetaOapg.properties.address_city: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["address_state"]) -> MetaOapg.properties.address_state: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["address_zip"]) -> MetaOapg.properties.address_zip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["address_line2"]) -> MetaOapg.properties.address_line2: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["address_line1", "address_city", "address_state", "address_zip", "address_line2", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["address_line1"]) -> MetaOapg.properties.address_line1: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["address_city"]) -> MetaOapg.properties.address_city: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["address_state"]) -> MetaOapg.properties.address_state: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["address_zip"]) -> MetaOapg.properties.address_zip: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["address_line2"]) -> typing.Union[MetaOapg.properties.address_line2, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["address_line1", "address_city", "address_state", "address_zip", "address_line2", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        address_line1: typing.Union[MetaOapg.properties.address_line1, str, ],
        address_state: typing.Union[MetaOapg.properties.address_state, str, ],
        address_zip: typing.Union[MetaOapg.properties.address_zip, str, ],
        address_city: typing.Union[MetaOapg.properties.address_city, str, ],
        address_line2: typing.Union[MetaOapg.properties.address_line2, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AddressFieldsUs':
        return super().__new__(
            cls,
            *args,
            address_line1=address_line1,
            address_state=address_state,
            address_zip=address_zip,
            address_city=address_city,
            address_line2=address_line2,
            _configuration=_configuration,
            **kwargs,
        )
