# coding: utf-8

"""
    Lob

    The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 

    The version of the OpenAPI document: 1.19.28
    Contact: lob-openapi@lob.com
    Created by: https://support.lob.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lob_python_sdk import schemas  # noqa: F401


class LinkList(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    Array of links to shorten.
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['LinkSingle']:
            return LinkSingle

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['LinkSingle'], typing.List['LinkSingle']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'LinkList':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'LinkSingle':
        return super().__getitem__(i)

from lob_python_sdk.model.link_single import LinkSingle
