# coding: utf-8

"""
    Lob

    The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 

    The version of the OpenAPI document: 1.19.28
    Contact: lob-openapi@lob.com
    Created by: https://support.lob.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lob_python_sdk import schemas  # noqa: F401


class Scans(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            ip_location = schemas.StrSchema
            scan_date = schemas.StrSchema
            __annotations__ = {
                "ip_location": ip_location,
                "scan_date": scan_date,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ip_location"]) -> MetaOapg.properties.ip_location: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scan_date"]) -> MetaOapg.properties.scan_date: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["ip_location", "scan_date", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ip_location"]) -> typing.Union[MetaOapg.properties.ip_location, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scan_date"]) -> typing.Union[MetaOapg.properties.scan_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["ip_location", "scan_date", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        ip_location: typing.Union[MetaOapg.properties.ip_location, str, schemas.Unset] = schemas.unset,
        scan_date: typing.Union[MetaOapg.properties.scan_date, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Scans':
        return super().__new__(
            cls,
            *args,
            ip_location=ip_location,
            scan_date=scan_date,
            _configuration=_configuration,
            **kwargs,
        )
