# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from lob_python_sdk.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    URL_SHORTENER = "URL Shortener"
    UPLOADS = "Uploads"
    CAMPAIGNS = "Campaigns"
    BANK_ACCOUNTS = "Bank Accounts"
    BUCKSLIPS = "Buckslips"
    CARDS = "Cards"
    TEMPLATE_VERSIONS = "Template Versions"
    TEMPLATES = "Templates"
    ADDRESSES = "Addresses"
    BILLING_GROUPS = "Billing Groups"
    CHECKS = "Checks"
    LETTERS = "Letters"
    POSTCARDS = "Postcards"
    SELF_MAILERS = "Self Mailers"
    CREATIVES = "Creatives"
    BUCKSLIP_ORDERS = "Buckslip Orders"
    CARD_ORDERS = "Card Orders"
    INTL_VERIFICATIONS = "Intl Verifications"
    US_VERIFICATIONS = "US Verifications"
    IDENTITY_VALIDATION = "Identity Validation"
    INTL_AUTOCOMPLETIONS = "Intl Autocompletions"
    QR_CODES = "QR Codes"
    REVERSE_GEOCODE_LOOKUPS = "Reverse Geocode Lookups"
    US_AUTOCOMPLETIONS = "US Autocompletions"
    ZIP_LOOKUPS = "Zip Lookups"
    ACCOUNTS = "Accounts"
    LOB_CREDITS = "Lob Credits"
    SNAP_PACKS = "Snap Packs"
    AUTHENTICATION = "Authentication"
    BETA_PROGRAM = "Beta Program"
    BULK_INTL_VERIFICATIONS = "Bulk Intl Verifications"
    BULK_US_VERIFICATIONS = "Bulk US Verifications"
    ERRORS = "Errors"
    EVENTS = "Events"
    GETTING_STARTED = "Getting Started"
    INTRODUCTION = "Introduction"
    MANAGE_MAIL = "Manage Mail"
    NATIONAL_CHANGE_OF_ADDRESS = "National Change of Address"
    RATE_LIMITING = "Rate Limiting"
    REQUESTS_AND_RESPONSES = "Requests and Responses"
    SDKS_AND_TOOLS = "SDKs and Tools"
    TEMPLATE_DESIGN = "Template Design"
    TEST_AND_LIVE_ENVIRONMENTS = "Test and Live Environments"
    TRACKING_EVENTS = "Tracking Events"
    US_VERIFICATION_TYPES = "US Verification Types"
    VERSIONING_AND_CHANGELOG = "Versioning and Changelog"
    WEBHOOKS = "Webhooks"
