# coding: utf-8

"""
    Lob

    The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 

    The version of the OpenAPI document: 1.19.28
    Contact: lob-openapi@lob.com
    Created by: https://support.lob.com/
"""

from lob_python_sdk.paths.bank_accounts.post import CreateNewBankAccountRaw
from lob_python_sdk.paths.bank_accounts_bank_id.delete import DeleteBankAccountRaw
from lob_python_sdk.paths.bank_accounts_bank_id.get import GetDetailsRaw
from lob_python_sdk.paths.bank_accounts.get import GetListRaw
from lob_python_sdk.paths.bank_accounts_bank_id_verify.post import VerifyBankAccountRaw


class BankAccountsApiRaw(
    CreateNewBankAccountRaw,
    DeleteBankAccountRaw,
    GetDetailsRaw,
    GetListRaw,
    VerifyBankAccountRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
