# coding: utf-8

"""
    Lob

    The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 

    The version of the OpenAPI document: 1.19.28
    Contact: lob-openapi@lob.com
    Created by: https://support.lob.com/
"""

from lob_python_sdk.paths.billing_groups.post import CreateNewGroupRaw
from lob_python_sdk.paths.billing_groups_bg_id.get import GetDetailsRaw
from lob_python_sdk.paths.billing_groups.get import ListRaw
from lob_python_sdk.paths.billing_groups_bg_id.post import UpdateAttributesRaw


class BillingGroupsApiRaw(
    CreateNewGroupRaw,
    GetDetailsRaw,
    ListRaw,
    UpdateAttributesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
