# coding: utf-8

"""
    Lob

    The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 

    The version of the OpenAPI document: 1.19.28
    Contact: lob-openapi@lob.com
    Created by: https://support.lob.com/
"""

from lob_python_sdk.paths.campaigns.post import Create
from lob_python_sdk.paths.campaigns_cmp_id.delete import Delete
from lob_python_sdk.paths.campaigns.get import List
from lob_python_sdk.paths.campaigns_cmp_id.get import Retrieve
from lob_python_sdk.paths.campaigns_cmp_id_send.post import Send
from lob_python_sdk.paths.campaigns_cmp_id.patch import Update
from lob_python_sdk.apis.tags.campaigns_api_raw import CampaignsApiRaw


class CampaignsApi(
    Create,
    Delete,
    List,
    Retrieve,
    Send,
    Update,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CampaignsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CampaignsApiRaw(api_client)
