# coding: utf-8

"""
    Lob

    The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 

    The version of the OpenAPI document: 1.19.28
    Contact: lob-openapi@lob.com
    Created by: https://support.lob.com/
"""

from lob_python_sdk.paths.identity_validation.post import Validation
from lob_python_sdk.apis.tags.identity_validation_api_raw import IdentityValidationApiRaw


class IdentityValidationApi(
    Validation,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: IdentityValidationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = IdentityValidationApiRaw(api_client)
