# coding: utf-8

"""
    Lob

    The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 

    The version of the OpenAPI document: 1.19.28
    Contact: lob-openapi@lob.com
    Created by: https://support.lob.com/
"""

from lob_python_sdk.paths.self_mailers.post import CreateNewSelfMailer
from lob_python_sdk.paths.self_mailers_sfm_id.get import GetDetails
from lob_python_sdk.paths.self_mailers.get import GetList
from lob_python_sdk.paths.self_mailers_sfm_id.delete import RemoveSelfMailer
from lob_python_sdk.apis.tags.self_mailers_api_raw import SelfMailersApiRaw


class SelfMailersApi(
    CreateNewSelfMailer,
    GetDetails,
    GetList,
    RemoveSelfMailer,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SelfMailersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SelfMailersApiRaw(api_client)
