# coding: utf-8

"""
    Lob

    The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 

    The version of the OpenAPI document: 1.19.28
    Contact: lob-openapi@lob.com
    Created by: https://support.lob.com/
"""

from lob_python_sdk.paths.us_autocompletions.post import GetSuggestions
from lob_python_sdk.apis.tags.us_autocompletions_api_raw import USAutocompletionsApiRaw


class USAutocompletionsApi(
    GetSuggestions,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: USAutocompletionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = USAutocompletionsApiRaw(api_client)
